### ISSUE TITLE
Metis menu doesn't close on click outside menu & opens in same place when opening mobile version

### ISSUE THREAD

**Issue by Scrabble96** [joomla/cassiopeia#191] opened 2020-10-21 16:35 UTC
### Steps to reproduce the issue
1. Using the #48 installation packaage dated 20th October, click a dropdown item in the front-end menu in large screen horizontal view.
2. As above, and without closing the menu, narrow the screen so that the horizontal menu disappears and you are presented with the burger.
Open the menu from the burger 

### Expected result
1. Click or tap outside the menu and the menu closes
2a. The menu should be presented as level 1 only.
2b. Click or tap outside the menu and the menu closes

### Actual result
1. Click or tap outside the menu does not close the menu
2a. The menu is open at the same point that the main horizontal menu was open
2b. Click or tap outside the menu does not close the menu

### System information (as much as possible)
Tested on Windows 10, Firefox and Chrome, plus Android phone.

**Comment by richard67** [comment] 2020-10-24 13:11
Not sure if we can fix that. Will investigate.

**Comment by Scrabble96** [comment] 2020-10-24 14:58
> 
> 
> Not sure if we can fix that. Will investigate.

In my own J4 dev template, each UL has its own id based on the parent item number, e.g. id="drop-111" (I've used 'drop' as it's a dropdown menu).

If I add `onclick="closeMainMenu"` to the main website wrapper and then use this JS, it will close the sub-menu when I click outside the menu if I have opened the sub-menu with id drop-103.

`function closeMainMenu() {`
`  document.getElementById("drop-103").classList.remove("show");`
`}`

However, if I try this:

`function closeMainMenu() {`
`	document.getElementsByTagName("UL").classList.remove("show");`
`}`

or this:

`function closeMainMenu() {`
`	x = document.getElementsByTagName("UL").classList.contains('show');`
`	x.classList.remove("show");`
`}`

It doesn't do anything. My JS experience is very limited, but it's a starting point.

**Comment by richard67** [comment] 2020-10-24 15:00
> In my own J4 dev template, each UL has its own id based on the parent item number, e.g. id="drop-111" (I've used 'drop' as it's a dropdown menu).

We will run into the problem with creating unique id properties when having that menu module more than once on a page, which we have discussed elsewhere already.

**Comment by Scrabble96** [comment] 2020-10-24 16:27
> 

> We will run into the problem with creating unique id properties when having that menu module more than once on a page, which we have discussed elsewhere already.

I don't want to target individual ids; I was just using one for testing purposes to see if I was on the right track. 
The JS works when targeting an ID but doesn't work if you target multiple elements. But I think that is just my inexperience with JS and I probably haven't written it correctly. I'm sure there must be a way to make it work. In fact, it needs a bit more code to change the button's aria-expanded to 'false' or the triangle stays pointing upwards when the sub-menu closes, i.e.

`setAttribute("aria-expanded", "false");`

**Comment by richard67** [comment] 2020-10-24 19:42
@Scrabble96 Regarding your 2nd point, narrowing the screen size and the menu keeps its expanded state: I see no issue in that. Normally you either have a desktop or a mobile device. On a mobile device you may change between portrait and landscape. This reducing of screen size so that it changes from desktop to mobile view is a scenario which happens ONLY during testing.

It might even be desired that the menu keeps its expanded state for the submenus when changing e.g. from portait to landscape or vice versa on a mobile device.

So for me only the issue remains that people expect when they click outside the menu then everything collapses.

Even this is in my opinion worth a question what is better UX: Let the menu keep its state or let it change its state when I tip by accident a few pixels to much left or right beside the menu instead of the menu and everything closes then.

**Comment by richard67** [comment] 2020-10-24 19:47
On the other hand I just see in some good example websites, e.g. the example which Brian had provided in his issue #125 , that it seems to be common to close the menu when clicking outside, so it seems to be good UX to do that.

I'll see what we can do for that.

**Comment by richard67** [comment] 2020-10-28 12:59
Related issues in the metismenujs repository:
- https://github.com/onokumus/metismenujs/issues/5 "API to collapse all active ULs" is a feature request by @ciar4n from 11 Oct 2018. There hasn't been any activity on it except that it has been categorized.
- https://github.com/onokumus/metismenujs/issues/3 "Submenu is not closing when user clicks outside of its container in horizontal menus." is a bug report from 9 Oct 2018. There is a long discussion on it which also suggest some solutions with own javascript. I'll check if we can do something like that here, too.

**Comment by richard67** [comment] 2020-10-28 13:01
@brianteeman Sorry for bothering you, but your experience and opinion is of high value for me, as you have done hundreds if not thousands of web sites where I have done one. What do you think, should the metismenu automatically collapse all open submenus when the user clicks outside the menu, or is it better for UX (and for that thing starting with "a" which I try to avoid to name now) to keep it open until the user explicitly closes it with the dropdown toggle? And if both is ok and it's just a matter of taste, what is your taste? Thanks in advance for any reply.

**Comment by brianteeman** [comment] 2020-10-28 13:09
@richard67 Flattery will get you everywhere

I can't think of any site I have ever been on where the dropdown menu stays open as it would obscure the content

In the joomla admin where the admin menu is in the sidebar in its own dedicated space then I would expect it to stay open

**Comment by richard67** [comment] 2020-10-28 13:13
> I can't think of any site I have ever been on where the dropdown menu stays open as it would obscure the content

@brianteeman Makes absolutely sense to me. Thanks for the reply and sorry if it was a too silly question.

So we have to fix that. I think we can.

**Comment by brianteeman** [comment] 2020-10-28 13:15
No such thing as a silly question. Just silly answers

**Comment by richard67** [comment] 2020-10-28 22:58
The first of the two issues, collapsing an open drop-down when clicking outside the menu, should be solved with pull request #210 .

Update 2020-11-03: The first of the two issues has been solved with #210 .

**Comment by richard67** [comment] 2020-11-03 10:24
Regarding the second issue see my comment above [https://github.com/joomla/cassiopeia/issues/191#issuecomment-716045367](https://github.com/joomla/cassiopeia/issues/191#issuecomment-716045367):

> Regarding your 2nd point, narrowing the screen size and the menu keeps its expanded state: I see no issue in that. Normally you either have a desktop or a mobile device. On a mobile device you may change between portrait and landscape. This reducing of screen size so that it changes from desktop to mobile view is a scenario which happens ONLY during testing.
>
>It might even be desired that the menu keeps its expanded state for the submenus when changing e.g. from portait to landscape or vice versa on a mobile device.

So I would say it's a "won't fix". @chmst @drmenzelit What do you think?

**Comment by chmst** [comment] 2020-11-03 10:52
agreed. This is an effect which is caused by the mix of installation data and later added sample data. In "real life" sites, a webdesinger constructs own menus.

**Comment by richard67** [comment] 2020-11-03 12:28
> agreed. This is an effect which is caused by the mix of installation data and later added sample data. In "real life" sites, a webdesinger constructs own menus.

@chmst Sorry, I don't understand the relation of that comment to my previous one. My comment refers to 2nd issue that the dropdowns of the metismenu remain in their status when resizing screen from desktop to mobile. How is that related to data?

**Comment by chmst** [comment] 2020-11-03 13:23
Sorry, my bad. I misunderstoode something. (screens sometimes would be really useful ..) 
And again - I agree that we can leave this as is.

**Comment by Scrabble96** [comment] 2020-11-16 17:03
Shall I close this?

**Comment by richard67** [comment] 2020-11-16 17:06
Yes

**Closed as completed** 2020-11-16 17:46 UTC
