### ISSUE TITLE
Remove underline for template title

### ISSUE THREAD

**Issue by chmst** [joomla/cassiopeia#181] opened 2020-10-14 14:51 UTC
### Steps to reproduce the issue
Add a Title in the template Params, it appears underlined but is not a link. This is misleading

![grafik](https://user-images.githubusercontent.com/1035262/96006122-709c0880-0e3d-11eb-8f79-674454138849.png)

**Comment by hans2103** [comment] 2020-10-21 21:26
Not able to reproduce the issue. 
I have checked out cassiopeia development branch and the title is an anchor.
<img width="689" alt="Schermafbeelding 2020-10-21 om 23 24 42" src="https://user-images.githubusercontent.com/639822/96788983-9f455080-13f4-11eb-9a0a-e6437605788e.png">

**Comment by chmst** [comment] 2020-10-21 22:12
You are right, so the cassiopeia need an undersore. But this is ugly.  undersore or undersore  all titles only on hover?

**Comment by hans2103** [comment] 2020-10-22 06:32
When a className is added to the link, the underscore will disappear

**Comment by richard67** [comment] 2020-10-24 07:03
@chmst I can't reproduce the issue either. If you still can, please test PR #198 , and if it solves it for you, leave a comment there with your test result and close this issue here. Thanks in advance.

**Comment by richard67** [comment] 2020-10-24 08:42
@chmst Silly me. I can reproduce the issue and confirm that PR #198 fixes it. You have to follow the title link so that it becomes active.

Closing as solved with pull request #198 .

**Closed as completed by richard67** 2020-10-24 08:42 UTC
