### ISSUE TITLE
Problem closing a sub-menu in MetisMenu

### ISSUE THREAD

**Issue by drmenzelit** [joomla/cassiopeia#29] opened 2020-08-17 18:01 UTC
### Steps to reproduce the issue
Install the the metismenu branch (https://github.com/joomla/cassiopeia/tree/4.0-dev-metismenu-frontend), create a menu with submenus (using menu heading as level 0) on position "menu" and alternative layout "metismenu". Try to open and close the submenu.

### Expected result
The submenu closes and disappears.

### Actual result
The submenu stay open or somehow visible.
The problem is related with the class "mm-collapsing", but because I not fit in javascript, I don't know how to debug it :-(

**Comment by richard67** [comment] 2020-08-17 18:10
You have run „npm ci“ to compile js and scss after having checked out the branch?

**Comment by drmenzelit** [comment] 2020-08-17 18:47
We are including the js file from media folder, so I think it is already compiled? But I checked also after running npm ci and the problem persists....

**Comment by chmst** [comment] 2020-08-17 19:37
Strange behaviour (npm ci done): Click on the parent - th submeu is not closed. Then hover the Submenu and it disappears

![metismenu](https://user-images.githubusercontent.com/1035262/90436905-c10f1800-e0d1-11ea-9721-66ccc4368836.gif)

**Comment by hans2103** [comment] 2020-08-18 07:01
I can confirm the strange behavior. I can click to open, cannot click second time to close. 

We are using MetisMenuJS, the same as implemented on Admin. 
We've added a trigger to let MetisMenuJS work.
https://github.com/joomla/cassiopeia/pull/26/files#diff-f84eb3e36ede591cb5c995c6e9aece74

When loading the page you can see that MetisMenuJS is loaded, because some extra classes are added by MetisMenuJS when clicking an item. 
But... 
The Joomla admin has much more javascript for admin-menu.js
https://github.com/joomla/cassiopeia/blob/4.0-dev/build/media_source/mod_menu/js/admin-menu.es6.js
Can anyone tell me why and are they needed to make this work on frontend too?

**Comment by richard67** [comment] 2020-08-18 07:34
I'm not a javascript expert so can't say right now what all is needed from the admin menu and what not.

It would need me a couple of hours to analyse that. I don't have this time before weekend.

Anyway, I think we should try to simplify that, remove all what is not really needed.

@chmst Do you know who was involved in making the admin menu, especially the js, so we can ask the right expert?

**Comment by chmst** [comment] 2020-08-18 08:22
@Hackwar did much of the work. in backend. Please Hannes, can you have a look here?

**Comment by chmst** [comment] 2020-08-18 11:45
Another issue is, that te parent for the 3rd lavel (tpye heading) has not arrow

**Comment by ciar4n** [comment] 2020-08-18 16:12
Test https://github.com/joomla/cassiopeia/pull/26#issuecomment-675572868

**Comment by chmst** [comment] 2020-08-26 08:56
closed as we have a PR

**Closed as completed by chmst** 2020-08-26 08:56 UTC
